// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace WinFormsDesafio2Entity.CompiledModels
{
    public partial class ContextModel
    {
        partial void Initialize()
        {
            var cliente = ClienteEntityType.Create(this);
            var fornecedor = FornecedorEntityType.Create(this);
            var pedido = PedidoEntityType.Create(this);
            var produto = ProdutoEntityType.Create(this);

            PedidoEntityType.CreateForeignKey1(pedido, cliente);
            ProdutoEntityType.CreateForeignKey1(produto, fornecedor);
            ProdutoEntityType.CreateForeignKey2(produto, pedido);

            ClienteEntityType.CreateAnnotations(cliente);
            FornecedorEntityType.CreateAnnotations(fornecedor);
            PedidoEntityType.CreateAnnotations(pedido);
            ProdutoEntityType.CreateAnnotations(produto);

            AddAnnotation("ProductVersion", "7.0.0");
            AddAnnotation("Proxies:ChangeTracking", false);
            AddAnnotation("Proxies:CheckEquality", false);
            AddAnnotation("Proxies:LazyLoading", true);
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
